SEGMENT_SIZE_SEC = 3
SAMPLING_RATE = 128
SEGMENT_WIDTH = SEGMENT_SIZE_SEC * SAMPLING_RATE
SEGMENT_HEIGHT = SEGMENT_SIZE_SEC * SAMPLING_RATE
CHANNEL_NUMBER = 16
EPOCHS = 3
BATCH_SIZE = 1
KFOLD_N_SPLITS = 2
